LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := wisky8735m_6_h

MODULES += app/mt_boot \
           dev/lcm


MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += SWCHR_POWER_PATH
DEFINES += MTK_ETA6005_SUPPORT
MTK_LCM_PHYSICAL_ROTATION = 180
CUSTOM_LK_LCM="nt35521_wxga_n080ice_dsi_vdo"
#nt35590_hd720_dsi_cmd_auo = yes

#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes

DEBUG := 2
BOOT_LOGO=wxga

#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y
#DEFINES += MACH_FPGA_NO_DISPLAY=y
DEFINES += MTK_GPT_SCHEME_SUPPORT
